### ISSUE TITLE
modelform raises IntegrityError instead of ValidationError

### ISSUE THREAD

**Issue by Hedde** [yourlabs/django-autocomplete-light#429] opened 2015-05-28 12:38 UTC
fork: https://github.com/Hedde/django-autocomplete-light
example app: /autocomplete_light/example_apps/modelform_admin_issue

Reproduction steps:

Add an Y model and leave the autosuggest field empty then hit save. A ValidationError is expected, yet an IntegrityError is raised

    Cannot assign None: "YModel.x" does not allow null values.

**Comment by jpic** [comment] 2015-05-28 22:27
Awesome !! Thanks for your report.

It's a bit weird that the YModel.x is non `null` while the form's field you've defined doesn't have `required=True`, so that's a but in your code.

However, after fixing that bug, I could reproduce your issue and create a fix in maybe 15 minutes so that's really fast.

Closing this ticket in favor of PR #430. Please try it out and if it works for you we can release rc3 as this was a regression caused by rc1 ;)

**Closed** 2015-05-28 22:28 UTC

**Comment by jpic** [comment] 2015-05-28 22:29
Sources:

https://docs.djangoproject.com/en/1.8/ref/models/fields/#null
https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.Field.blank
https://docs.djangoproject.com/en/1.8/ref/forms/fields/#required
