### ISSUE TITLE
demo site link from github main page returns an error from PythonAnywhere

### ISSUE THREAD

**Issue by rwillmer** [yourlabs/django-autocomplete-light#353] opened 2015-01-08 19:41 UTC
https://github.com/yourlabs/django-autocomplete-light has a link to 'Live demo graciously hosted by PythonAnywhere,'.

This link returns 'Error code: Unhandled Exception' on an error page

**Comment by jpic** [comment] 2015-01-20 14:37
Duplicate of #322

**Closed by jpic** 2015-01-20 14:37 UTC
