### ISSUE TITLE
left parenthesis ("(") and ampersand ("&") characters are ignored

### ISSUE THREAD

**Issue by jindrichjindrich** [yourlabs/django-autocomplete-light#394] opened 2015-04-07 14:29 UTC
Due to the fact that event.keyCode for "(" is the same as for a KEY_DOWN (40) and event.keyCode for "&" is the same as for a KEY_UP (38) those characters are ignored when an attempt to enter them in a search string is made.

I solved it by replacing each occurrence of e.keyCode with _keyCode(e) in autocomplete.js.

_keyCode is a function:

function _keyCode(e) { return (e.charCode + 1) * e.keyCode; }

**Comment by blueyed** [comment] 2015-04-08 02:46
That might be a more generic fix for https://github.com/yourlabs/django-autocomplete-light/issues/294 (which is fixed in master).

**Comment by blueyed** [comment] 2015-04-08 16:03
Can you please try the fix from https://github.com/yourlabs/django-autocomplete-light/pull/398 ?

I think that this fix goes into the same direction, by using `e.which` instead of `e.keyCode` (which prefers `e.charCode`, too).

**Comment by yliharma** [comment] 2015-04-09 08:13
Nope, #398 broke the ampersand again!

**Comment by blueyed** [comment] 2015-04-09 13:43
@yliharma 
Thanks for reporting back.  I see now what the issue is, and it's not related to Mac, but Webkit in general (I can confirm it here).

@jindrichjindrich 
The issue is fixed in Git / the current rc already.

I will add a comment to the code, and use the `charCode == 0` check instead, which appears to be more sensible to me.

**Closed** 2015-04-09 13:47 UTC
Labels: bug

**Comment by yliharma** [comment] 2015-04-09 14:00
Have you tried it with non-webkit browsers, like Firefox or our "old friend" Internet Explorer?

**Comment by blueyed** [comment] 2015-04-09 14:05
It works with Firefox, but haven't tried IE.

**Comment by yliharma** [comment] 2015-04-09 16:07
Perfect for me :+1:

**Comment by jpic** [comment] 2015-04-11 18:21
Excellent, fix released in 2.1.0rc3.
