### ISSUE TITLE
Paste breaks autocomplete

### ISSUE THREAD

**Issue by MaZZly** [yourlabs/django-autocomplete-light#288] opened 2014-06-09 07:00 UTC
Pasting text breaks the autocomplete..

First paste doesn't do anything (no text pasted), second paste works (text pasted) but then afterwards when text is modified autocomplete is not updated.

The DOM gets multiple spans ".autocomplete-light-text-widget" appended after input (which blocks the one that is updated)

A simple fix atm is with css:
```css
span.autocomplete-light-text-widget+span.autocomplete-light-text-widget {
    display: none!important;
}
```

But the paste event should probably be handled in the yourlabsautocomplete code..

**Comment by jpic** [comment] 2015-04-07 14:18
Could not reproduce with Chromium nor Firefox, closing.

**Closed by jpic** 2015-04-07 14:18 UTC
Labels: bug
