### ISSUE TITLE
is it possible to order a many-to-many field?

### ISSUE THREAD

**Issue by pcompassion** [yourlabs/django-autocomplete-light#404] opened 2015-04-15 08:57 UTC
When using autocomplete-light in django admin, it is natural to give them orders. (The first item we add is the first item in order)

Is there a way to persist that information somehow so that when querying the field, I can get data in the order I intended. 
(User might reorder the field by deleting and adding items).

**Comment by pcompassion** [comment] 2015-04-15 09:41
I guess I can make `through` table, and assign count as index.

**Comment by pcompassion** [comment] 2015-04-15 09:53
oh. shouldn't have been so hasty to close it.

When I have `through` parameter, django admin won't show the many-to-many field, and neither autocomplete_light form will show up..

**Comment by jpic** [comment] 2015-05-17 13:57
Well now that autocomplete-light keeps the order the user selected items in, there should be no problem for you to save the order in a form save() method or something.

It would be awesome if I could reproduce this, see http://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/faq.html#how-to-ask-for-help

**Comment by jpic** [comment] 2015-11-21 13:51
autocomplete-light keeps the order the user selected items in, it was really hard since we have to generate raw SQL that would work in EVERY project and weird cases ^^

Closing, please re-open if you have questions.

**Closed by jpic** 2015-11-21 13:51 UTC
Labels: pending user feedback
