### ISSUE TITLE
Is there a way to have TextField only insert the value of the 'data-value' attribute into the Input field?

### ISSUE THREAD

**Issue by Kabal** [yourlabs/django-autocomplete-light#317] opened 2014-08-29 06:07 UTC
I kind of want to search for stuff, display the id + some other data, but the only place an id in a text field

TextField seems put the entire text contents of my choice template into the text field.

I tried modifying my ModelForm to use the ChoiceWidget instead which almost works, except when editing a 'bound' form as the single value doesn't map to the ChoiceWidget correctly.

**Comment by jpic** [comment] 2015-04-07 03:15
Duplicate of #338

**Closed by jpic** 2015-04-07 03:15 UTC
