### ISSUE TITLE
livedemo error 500

### ISSUE THREAD

**Issue by kinwolfqc** [yourlabs/django-autocomplete-light#888] opened 2017-07-14 23:11 UTC
The livedemo doesn't work.  Error 500

**Comment by oonid** [comment] 2017-09-08 17:33
HTTP 500 Internal Server Error http://dal-yourlabs.rhcloud.com/
anyone know what happened?
any other alternative on live DAL demo?
thank you.

**Comment by stvnw** [comment] 2017-09-13 17:52
Duplicate of https://github.com/yourlabs/django-autocomplete-light/issues/846

**Comment by jpic** [comment] 2017-09-13 21:23
Note that installing it is documented: http://django-autocomplete-light.readthedocs.io/en/master/install.html#install-the-demo-project

Do you think it would help update the link to the demo to this documentation ?

**Comment by stvnw** [comment] 2017-09-13 21:36
It's clear how a user can install the demo on their own machine, and that works fine.

The issue is just that the demo hosted at RedHat (as referred to in README) is broken. If it can't or won't be fixed, perhaps the reference in README should be removed.

**Comment by jpic** [comment] 2017-09-14 09:35
Or you can have credentials if you want to have some fun hacking the github->travis->openshift pipeline i've maintained for a bit more than a year or so ;)

**Comment by jpic** [comment] 2017-09-14 09:37
Now, I'm doing docker on my own servers, I could add the demo project but then that means I should have some sort of business model with DAL, but i don't think anybody would be interested in buying a professional license for a hundred bucks a year or something ^^

**Comment by jpic** [comment] 2017-09-14 09:41
Actually my current pipeline is made with gogs running inside docker, because it's really damn fast, cloning is damn fast too (github.com, gitlab.com: too slow for me), and then it's my hosted drone.io instance, also super fast, in charge of the build/test/deploy pipeline. I'd need to bill something like 50€/month all included to keep on maintaining the demo on my own servers.
So really, what do we want to do, just remove the link, or make it happen ?
Discussion open for comments :dancing_men:

**Comment by stvnw** [comment] 2017-09-15 20:43
It's your call. I am unable to commit to maintaining the RedHat instance. I think though, that anyone interested in integrating DAL into their project will already be familiar enough with Django and will have a suitable development environment, such that spinning up the demo on their own box would be trivial. Furthermore, I don't think a hosted demo is essential to selling people on the concept / benefits of autocomplete. It's nice to have, but I think a fair case can be made for dropping the live demo if the resources aren't there to manage it.

**Comment by jpic** [comment] 2017-09-15 21:21
Why is this my call ? Why would I have to care ? You said it, the market is really good these day for open source software hackers because creation is so rewarding in a capitalist system. What are we looking at then ? Absolutely nothing, just a broken link, but guess what, there's also someone having fun at the party at the exact very same time and it may or it may not be a poet dreaming about live fucking working demos for elementary modules like autocompletion in your framework because guess what we're taking a trip in the train for 2017 which is like so far away from the good old times of netscape and internet explorer
I really just care about CI results and there could be some easy contribution to fix the QA job which might have taken as long as typing this message to submit in a pull request if only you have the hub command which of course you have and if you want to remove the link to my broken demo go ahead and make that pull request while I'm running the test suite with Python 3.6 and looking at what looks to be a selenium wait taking for ever and ever and ever and ever in select2_foreign_key/test_functional.py::AdminForeignKeyTestCase::test_can_add_another_option
Thanks again for your feedback ;)

**Comment by jpic** [comment] 2017-09-15 21:31
And what are we looking at ? Where are we ? This is the jungle. Software code is a jungle, you have lots of living things and dangerous things and guess what a ton of bugs so yeas let's fix them you have my call to remove the broken link, PR will be accepted, thanks to you, we can start making things better, one broken link at the time, and one day, society will also take the train to a world of technology and perhaps then will we be able to create the first liquid democracy experiment at scale and guess what then again you're going to need autocompletion in your framework because remember, you took the train to 2017

**Comment by jpic** [comment] 2017-09-22 18:54
Back after some thinking about hosting the demo on my own infra, or rather, the infra I'm building for my new software company.
I thought, does this really deserve a hosted demo at all ? After all, this is 2017, doing autocompletion in Django should be a piece of cake. This is the reason why we started developing CRUDLFA+ and you can see the video demo here: https://www.youtube.com/watch?v=lGqeXp6zeo8
Since DAL is going to be something you don't even configure or worry about, and just have with CRUDLFA+, then we should probably have a hosted demo of CRUDLFA+ rather than django admin + DAL.

**Closed** 2018-03-20 16:28 UTC
