### ISSUE TITLE
'vendor' folder is missing

### ISSUE THREAD

**Issue by guettli** [yourlabs/django-autocomplete-light#620] opened 2016-03-07 07:36 UTC
In 3.0.1 I get 404-File-not-Found for the JS files located in the 'vendor' directory.

Yes, I have run "collectstatic" :-)

**Comment by senoadiw** [comment] 2016-03-07 09:34
+1, installed 3.1.0 with pip and getting 404 for the following:
* http://localhost:8000/static/autocomplete_light/vendor/select2/dist/css/select2.css
* http://localhost:8000/static/autocomplete_light/vendor/select2/dist/js/select2.full.js

The /static/autocomplete_light dir after collectstatic (no vendor dir created):
* autocomplete.init.js
* jquery.init.js
* select2.css
* select2.js

**Comment by jpic** [comment] 2016-03-07 10:14
Tried git submodule update --init ?

**Comment by senoadiw** [comment] 2016-03-07 10:35
@jpic comparing with 3.0.4 release on PyPI it looks like 3.1.0 is missing the vendor dir in src/dal_select2/static/autocomplete_light/

**Comment by jpic** [comment] 2016-03-07 11:06
Thanks !!​

Fixed in 3.1.1

I guess we need to find a curative solution against that, perhaps
automating releases ^^

Sorry for the delay.

Best

**Comment by senoadiw** [comment] 2016-03-07 11:17
@jpic thanks! I can confirm 3.1.1 release solves this issue.

**Comment by guettli** [comment] 2016-03-08 20:10
Yes, fixed in 3.1.1
Thank you very much!

**Comment by andybak** [comment] 2019-01-22 08:54
Seems to have reappeared in 3.3.2

Steps to recreate:

1. Download the 3.3.2 gz file from PyPi
2. Search for directories called "vendor"

There's only one and it's in dal_jal. However dal_select2/widgets.py line 57 references 'admin/css/vendor/select2/select2%s.css' % extra

**Comment by andybak** [comment] 2019-01-22 09:16
Yes. Just to need to think of a tidy way to handle forward and backwards compat.

How about keeping the "missing" files in a separate dal app: "dal_legacystatic" or similar?

The docs could then clearly state: "If you're using Django < 2.0 then add dal_legacystatic to installed apps.

**Comment by andybak** [comment] 2019-01-23 13:44
OK. Hopefully this does the trick: https://github.com/yourlabs/django-autocomplete-light/pull/1085

**Comment by jpic** [comment] 2019-01-29 19:26
Congrats @andybak for fixing the issue in master with #1085 :champagne: 

 Please @all someone could confirm the fix works for the with master ?

Or do you prefer a release right away ?

**Comment by mpeuss** [comment] 2019-04-09 09:00
@jpic 
We tested the fix and it seems to be working. When will you release a new version?

**Comment by jpic** [comment] 2019-04-10 23:47
Released in 3.3.4

Please re-open in case of regression

Thanks for your input and have a great day :+1:

**Closed by jpic** 2019-04-10 23:47 UTC

**Comment by gamesbook** [comment] 2020-10-17 15:51
Encountering this same issue - has it been patched?
