### ISSUE TITLE
error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by brycenesbitt** [yourlabs/django-autocomplete-light#284] opened 2014-06-04 03:35 UTC
For reasons I don't fully understand, about one in 50 of django-autocomplete-light's ajax queries return with Broken Pipe on my server:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
Exception happened during processing of request from ('127.0.0.1', 43082)
[03/Jun/2014 20:20:26] "GET /ac/?q=this+is+a+test+sdklf HTTP/1.1" 200 12
```
This would go unnoticed in most cases, except for this global error handler:

```
$( document ).ajaxError(function(e,jqXHR) {
  alert('An error has occurred.  Please reload the page.  If the problem persists, please report to the administrators. Code ' + jqXHR.status + '.');
});
````

Is there a way to override the default error handler for yourlabsAutocomplete ?
See http://stackoverflow.com/a/7436344/311364
Any clue on the Broken pipe?

**Comment by jpic** [comment] 2015-04-07 03:19
It looks like a bug in your server ... please repoen otherwise.

**Comment by jpic** [comment] 2015-04-07 03:20
Did you check if throttling is working correctly on the client side ? thanks B)

**Comment by jpic** [comment] 2015-06-01 00:31
There's an accepted answer on the stackoverflow: http://stackoverflow.com/questions/7436195/disabling-some-jquery-global-ajax-event-handlers-for-a-request/7436344#7436344

Closing.

**Closed by jpic** 2015-06-01 00:31 UTC

**Comment by brycenesbitt** [comment] 2015-06-01 01:41
That answer is about ignoring the error... rather than preventing the error.
But I'm no longer working on that project so can't comment if it's still happening.

**Comment by jpic** [comment] 2015-06-01 08:48
The issue is about reporting an error with your specific infrastructure .. rather than provide steps to reproduce it or a test case.

Please reopen when you're able and willing to provide more detail.

**Comment by jpic** [comment] 2015-06-01 08:59
I've opened a followup issue on the new repo for the JS: yourlabs/jquery-autocomplete-light#3

IMHO, there is no way no one can do anything about it, but just in case I'm leaving it open until the repo is too polluted with issues which we can't do anything about.

IMHO, it's an HTTP request that autocomplete.js made but canceled in favor of a newer HTTP request. With proper server configuration I don't think this would happen but really, I can't reproduce so ...

Thanks for the detailed report and helpful attempt to help.

**Comment by jpic** [comment] 2015-06-01 09:09
Sincerely I closed it because I've been through it many times while triaging and always came to the same conclusion: not enough detail, can't reproduce the user was focused on working around this in his error handler rather than trying to contribute a proper fix.

You should understand that we're several volunteers going through the issue list and every time there's an issue that's not fixable (not enough detail, not reproducible, user didn't really care to help us) then it's time the volunteer could have used on a fixable issue (detailed, reproducible, with helpful user feedback).

As far as I'm concerned we don't even have proof there's a bug in autocomplete-light here. This might be just a throttling setting in the JS which should be increased to not break under-sized servers. Who can tell really. Anyway, it's time for me to move on to issues which can potentially be reproduced, tested and fixed.

All I can say for now is that the JS has been extracted as a standalone jQuery plugin and maybe someone in the JS community will be able to fix something related.

I hope these explanations are sufficient for your understanding and that you will post what you think I should have done instead of that.

Have a good day

**Comment by blueyed** [comment] 2015-06-02 00:44
> Have a good day

Same for you! :)

**Comment by jpic** [comment] 2015-06-02 08:09
Having a great time at the conference, you should be there bro !!
