### ISSUE TITLE
Missing simple way to build Autocomplete in v3

### ISSUE THREAD

**Issue by ebertti** [yourlabs/django-autocomplete-light#571] opened 2016-02-04 16:38 UTC
In v2 you can made great autocomplete as:

``` python
class CustomerAutocomplete(al.AutocompleteModelBase):
    search_fields = ('id', 'user__name', 'user__email',)
    split_words = 'or'
    choices = Customer.objects.select_related('user')
```

this way, I don't need to worry about split words, build queries or make custom urls for each autocomplete.

I like a lot of things in new version(like using select2), but I miss this simple way to build autocomplete.

**Comment by jpic** [comment] 2016-02-04 16:57
Did you know that with this configuration, all your Customer database is available publicly on the web ?

**Comment by jpic** [comment] 2016-02-04 16:59
That being said, I have nothing against adding a configurable view in src/dal/views.py, if you wish to contribute it, all I'm asking is that it does not by made the default, for security reasons ;)

**Comment by ebertti** [comment] 2016-02-04 17:11
I know that :) I just make a example that I miss on new version. I have my mixin to make it more security. Don't worry about it.

That was more simple than now. 

Now I need to make everything. split, what fields to use using code and register the autocomplete widget on every form.

And in the old style, you can make your own if you want, is not mandatory.

**Comment by jpic** [comment] 2016-02-04 17:30
First things first, **nobody** is going to prevent you from using v2. It has Django 1.8 and 1.10 support, so we'll do our best to support it as long as 1.8 and 1.10.

Thanks for commenting about security, imagine the disaster if some new user was just going to copy the example you posted without thinking about it :D 

Anyway, seems like we agree that configurable views would be easy to add, but hey why not use [django-search-views](https://github.com/bianchimro/django-search-views/blob/master/searchlist_views/search.py) and contribute to that ? It has search_fields and order_field, just like you want, and it's reusable, in autocompletes, in views, everywhere ! Example:

```
from searchlist_views.views import LoginRequiredMixin, SearchListView

class YourAutocomplete(LoginRequiredMixin, SearchListView, Select2QuerySetView):
    search_fields = ('id', 'user__name', 'user__email',)
    queryset = Customer.objects.select_related('user')
    order_field = None
    # split_words, should better be "or" here by default, because i completely fail to see if there would be a use case for anything else than "or" ^^
```

The magic form is another topic, I don't know if you ever tried to debug it, but it is extremely hard.

On the forms.py of the master branch, I see 80 commits, apart from @blueyed who helped by cleaning imports and docstrings, it's all mine. Would you like to make an estimate of man-hour that was put in something that is still not supported by Django, and that triggers weird bugs like #550 ?  Maybe you could volunteer to fix #550 which @raratiu kindly closed even though it's still there and reproductible ?

We can add the magic form again, but it must not be the default, it could be in src/dal_magic. To know which autocomplete to use by default, we could just iterate over the registered urls and figure out the best for default.

**Comment by jpic** [comment] 2016-02-04 17:51
> And in the old style, you can make your own if you want, is not mandatory.

I don't understand what you mean here, we're talking about basic django views here, there's nothing preventing you from using the mixings and doing your own.

Please understand that I'm trying to have something that works and is secure by default, so that I can move on with my life, work on [activism](https://github.com/political-memory) [projects](https://github.com/societecitoyenne) and work on [projects](https://github.com/francepremium) [that](https://github.com/hearo) [pay](https://github.com/novapost). For this app, I had a bit of money in 2012 and 2013, but nothing since then. So either contribute the features you want, either find a business model of some sort, either join me in spending night maintaining it and supporting users :)

**Comment by jpic** [comment] 2016-02-05 18:27
Please take discussion about the magicform in #579 

Waiting for a PR on configurable views to close this issue now, @ebertti are you up for it ? ;)

**Comment by jpic** [comment] 2016-02-07 01:37
Could you please review the design of the model form metaclass for v3 in #579 ?

Thanks.

**Comment by jpic** [comment] 2016-12-22 03:05
Hi !

Could you please take a look at this trivial patch to Django and let me know if you think this would work ?

https://github.com/django/django/pull/7723

Thanks !!

**Comment by jpic** [comment] 2021-11-26 14:05
Hi @ebertti 

We have a simple way now in an external app yourlabs/djhacker.

It solves the same problem, except extremely well and with extremely little code, which makes it extremely more maintainable than the metaclass soup we had in v2.

As such, you can already start migrating to v3 before we deprecate v2.

Best

**Closed** 2021-11-26 14:07 UTC
