### ISSUE TITLE
error when using autocomplete_light.ChoiceField

### ISSUE THREAD

**Issue by zhiyajun11** [yourlabs/django-autocomplete-light#410] opened 2015-05-05 10:28 UTC
My autocomplete is :

    class ProfessionAutocomplete(autocomplete_light.AutocompleteListBase):
        choices = []
        def choices_for_request(self):
            self.choices = ['dae', 'abc', 'daa']
            return super(ProfessionAutocomplete, self).choices_for_request()

Form is :

    from django import forms
    class RegisterForm(forms.Form):
        profession = autocomplete_light.ChoiceField('ProfessionAutocomplete')

View is :

    def test(request):
        if request.method == 'POST':
            # create a form instance and populate it with data from the request:
            f = RegisterForm(request.POST)
            # check whether it's valid:
            if f.is_valid():
                return HttpResponseRedirect('/thanks/')
        else:
            f = RegisterForm()
        return render(request, 'admin_crm/register_document_edit.html', {'form':f})

However, when I post the resquest with 'dae' as the profession, 'f.is_valid()' failed saying that 'dae' is not a valid choice. What the matter?

**Comment by jpic** [comment] 2015-05-11 15:04
What versions ?

Maybe Django is passing unicode and it can't compare with items which are in your str list.

**Comment by zhiyajun11** [comment] 2015-05-12 12:18
My django version is 1.5.2, python 2.7.5, mac os, firefox browser. 
I think it has nothing to do with compare between items in my str list and django unicode, because when I stepped into the error , I found that the choice list of  autocomplete_light.ChoiceField, which was actually empty, didn't change when the ProfessionAutocomplete instance's choices field changed due to override of choices_for_request method. So the error seems to be reasonable.
I think this is a bug. What do you think?

**Comment by jpic** [comment] 2015-05-12 12:25
I think that the problem is that you haven't overridden [choices_for_values()](https://github.com/yourlabs/django-autocomplete-light/blob/c5c66aa9547b79fb90e25a8211f183ba382d78c4/autocomplete_light/autocomplete/list.py#L36). So choices_for_values will use `choices=[]`.

**Comment by zhiyajun11** [comment] 2015-05-13 02:44
I think you haven't got my point.
The `choices` variable of `AutocompleteListBase` have been dynamic already. However, the `choices` variable of `ChoiceField`, which is assigned at the `__init__` period of `ChoiceField`, is still static. That's why **'dae' is not a valid choice** show up.

**Comment by jpic** [comment] 2015-05-13 09:05
On Wed, May 13, 2015 at 4:44 AM, zhiyajun11 <notifications@github.com>
wrote:

> The choices variable of AutocompleteListBase have been dynamic already.
> However, the choices variable of ChoiceField, which is assigned at the
> __init__ period of ChoiceField, is still static. That's why *'dae' is not
> a valid choice* show up.
>
I'm sorry, but choices_for_request() is for the autocomplete view to render
a list of choices to the user in JS. validate_values() is for the
autocomplete widget to validate choices, so it should be the root cause of
the validation problem.

http://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/api.html#autocomplete_light.autocomplete.base.AutocompleteInterface.validate_values
http://django-autocomplete-light.readthedocs.org/en/stable-2.x.x/api.html#autocomplete-class-api

As I said, that:

```
class ProfessionAutocomplete(autocomplete_light.AutocompleteListBase):
    choices = []
    def choices_for_request(self):
        self.choices = ['dae', 'abc', 'daa']
        return super(ProfessionAutocomplete, self).choices_for_request()
```

Is wrong, because **obviously** ``choices`` is set only in one method, and
not in the other. It

If you want to continue that path, override validation.

-- 
http://yourlabs.org <http://blog.yourlabs.org>
Customer is king - Le client est roi - El cliente es rey.

**Comment by jpic** [comment] 2015-05-13 09:12
> The choices variable of AutocompleteListBase has been dynamic already. 

That's not how it works. You can't set some instance variable in one request (ajax GET request), and then expect it to still be there in another request (form POST submit).

**Comment by zhiyajun11** [comment] 2015-05-13 15:41
def validate(self, value):
        """
        Wrap around Autocomplete.validate_values().
        """
        super(FieldBase, self).validate(value)

        # FIXME: we might actually want to change the Autocomplete API to
        # support python values instead of raw values, that would probably be
        # more performant.
        values = self.prepare_value(value)

        if value and not self.autocomplete(values=values).validate_values():
            raise forms.ValidationError('%s cannot validate %s' % (
                self.autocomplete.__name__, value))
The above code, which is the method of FieldBase of autocomplete-light, shows that it failed at `super(FieldBase, self).validate(value)` , in which is the validation of django's ChoiceField, before `validate_values()`. That's my problem and what I mean  :).
Maybe I should define my own field to meet my needs.

**Comment by jpic** [comment] 2015-05-14 17:18
Nice catch !

There's even a docstring issue there because it doesn't mention the super
call.

It would probably have been better in the beginning to pass the field
instance to the autocomplete instance in that code and let
`Autocomplete.validate_values()` call `field.validate(value)`.​ It's a bit
a harsh BC break but might be a good idea for v3.

A perhaps simple way would be to add a field attribute, ie.
ChoiceField('FooAutocomplete', skip_field_validation=True).

What do you think ?

**Comment by jpic** [comment] 2015-05-15 02:12
I think that fix works, but I can't release it without making a proper security audit.

**Comment by zhiyajun11** [comment] 2015-05-15 06:50
>It would probably have been better in the beginning to pass the field
instance to the autocomplete instance in that code and let
`Autocomplete.validate_values()` call `field.validate(value)`.​ It's a bit
a harsh BC break but might be a good idea for v3.

That's will be fine. But it's not an easy job based on current structure. Hoping for v3 and autocomplete-light is really a nice project. Good luck.

**Comment by jpic** [comment] 2015-05-17 13:49
Closing in favor of PR #416 which should be in the next release.

**Closed by jpic** 2015-05-17 13:49 UTC

**Comment by jpic** [comment] 2015-05-26 09:07
Could you try with 2.2.0rc1 which was [released yesterday](http://blog.yourlabs.org/post/119860038918/django-autocomplete-light-2-2-0rc1-release-notes) ? 

Thanks.

**Comment by zhiyajun11** [comment] 2015-05-27 03:27
The backend seems to go well. But there is a js error in the front-end, which result in the disappearing of  prompt box. The error is:

    ReferenceError: isOpera is not defined
    autocomplete.js line 82
My browser is firefox.
