### ISSUE TITLE
Collectstatic error with whitenoise on 3.9.5 (same as #1281)

### ISSUE THREAD

**Issue by qsebas** [yourlabs/django-autocomplete-light#1328] opened 2023-05-12 02:47 UTC
the bug was described in the closed issue #1281 but it was not resolved

a fresh new django project with whitenoise and django-autocomplete-light in installed-app will throw the following error

```
The CSS file 'vendor/select2/docs/themes/learn2/css/font-awesome.min.css' references a file which could not be found:
  vendor/select2/docs/themes/learn2/fonts/fontawesome-webfont.woff2

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
```
the wierd thing is if I downgrade to 3.8.2, it works, but if I upgrade again to 3.9.5 it continues to work (even if I delete static folder)

to be sure to reproduce the error I have made a dockerfile, you can reproduce the error with a simple
```bash
docker build .
```
Here is the full project with all files needed to reproduce the error
[dal-static-error.zip](https://github.com/yourlabs/django-autocomplete-light/files/11458424/dal-static-error.zip)

**Comment by mattbuff-nynhp** [comment] 2023-05-12 02:57
Attempting to narrow down the problem: versions 3.9.4 and 3.9.5-rc1 work.

Upgrading to versions >= 3.9.5-rc2 causes collectstatic to fail.

**Comment by qsebas** [comment] 2023-05-12 03:14
No, I've tried with all versions from 3.9.0 to 3.9.5 and all fails, you can try it with the zip file changing the Pipfile and rebuilding the docker

**Comment by qsebas** [comment] 2023-05-12 13:02
sory!

I dind't realize that i have a ~= in the Pipfile, so even I ve changed the version I was allways using 3.9.5

I can confirm you 3.9.4 is working well

**Comment by jpic** [comment] 2023-05-12 15:47
We are not supposed to use git modules anymore since a82d1501c3c7b912e98c69a50b71a1c9802f31d6

But, apparently releases worked better on dirty repositories that still had a copy of the select2 submodule :facepalm: 

Unfortunately, I can't delete the release like last time because of https://github.com/pypi/support/issues/2788 as such, I'm trying to find a reasonable mitigation to make another release in the hour.

**Comment by jpic** [comment] 2023-05-12 15:49
BTW, what Django version are ya'll on?

**Comment by mattbuff-nynhp** [comment] 2023-05-12 17:42
3.2.19

**Comment by jpic** [comment] 2023-05-12 17:43
Thanks! Is it fixed for you with 3.9.7?

**Comment by mattbuff-nynhp** [comment] 2023-05-12 17:52
Confirmed - fixed in 3.9.7.
Thank you!

**Comment by jpic** [comment] 2023-05-12 18:15
Thanks! What a relief :rofl: 

So, the only preventive bugfix and the last one we can do for this repo, is make github action to do the [npm build](https://github.com/yourlabs/django-autocomplete-light/commit/a435ae8f0aada6030c217a8539abc66223ac014a) 

But it fails miserably to let npm copy a file because of a proclaimed permission error nevermind the fact that copying the file in bash in the above lines works perfectly as it should:

![2023-05-12-200915_846x926_scrot](https://github.com/yourlabs/django-autocomplete-light/assets/94636/24003b1f-8680-42a8-999f-009c79413517)

See full logs in [job #33337](https://github.com/yourlabs/django-autocomplete-light/actions/runs/4961726215/jobs/8878883337)

Any idea welcome!

**Comment by neofutur** [comment] 2023-05-16 19:41
cp node_modules/select2/dist/css/select2.css node_modules/select2/dist/css/select2.min.css 'src/dal_select2/static/vendor/select2/dist/css/*.css' 
have no meaning

the folder 'src/dal_select2/static/vendor/select2/dist/css/*.css is undefined / is not a folder

you probably want : 
cp node_modules/select2/dist/css/select2.css node_modules/select2/dist/css/select2.min.css src/dal_select2/static/vendor/select2/dist/css/ 
( if src/dal_select2/static/vendor/select2/dist/css/  is a real existing folder ) 
but anyway src/dal_select2/static/vendor/select2/dist/css/*.css  is not a valid destination folder for the cp command

**Comment by mmpx12** [comment] 2023-05-16 21:02
```diff
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,28 +1,35 @@
 name: Clean release
 run-name: ${{ github.actor }} release
-on: push
+on: 
+  push:
+    tags:
+      - '*'
+
 jobs:
   pypi-release:
     runs-on: ubuntu-latest
     container:
       image: yourlabs/python
+      options: --entrypoint /usr/sbin/bash
     steps:
     - name: Check out repository code
       uses: actions/checkout@v3
     - name: debug this crazy environment
       run: |
-        set -x
-        npm install
-        npm run build
+        workdir=$(pwd)
+        chown -R 1000:1000 "$workdir"
+        su - app -c "cd $workdir && npm install && npm run build"
     - name: Update version in setup.py and docs/conf.py
       run: |
         sed -i "s/version=[^,]*,/version='${GITHUB_REF##*/}',/" setup.py
         sed -i "s/release = [^,]*,/release = '${GITHUB_REF##*/}'/" docs/conf.py
-        sed -i 's/version": "[^"]*"/version": "$short"/' package.json
         short=$(echo ${GITHUB_REF##*/} | grep -Eo '[^.]+\.[^.]+')
+        sed -i 's/version": "[^"]*"/version": '\"$short\"'/' package.json
         sed -i "s/version = [^,]*,/version = '${GITHUB_REF##*/}'/" docs/conf.py
...
```

Avec ca normalement c'est bon. Mais à cause de `short=$(echo ${GITHUB_REF##*/} | grep -Eo '[^.]+\.[^.]+')` ca ne peut marcher que avce les tags:

```sh
echo 'master' | grep -Eo '[^.]+\.[^.]+' 
echo $?
1
```

**Comment by jpic** [comment] 2023-05-30 09:35
I think we got it to work now, I guess I owe some friends some :beers: now :rofl: 

https://github.com/yourlabs/django-autocomplete-light/actions/runs/5066646261/jobs/9096712238

**Closed by jpic** 2023-05-30 09:35 UTC
