### ISSUE TITLE
autocomplete field adds extra blank area

### ISSUE THREAD

**Issue by orges** [yourlabs/django-autocomplete-light#255] opened 2014-03-11 21:25 UTC
autocomplete field generates a html like that:
![screen shot 2014-03-11 at 11 19 36 pm](https://f.cloud.github.com/assets/1516018/2391212/f296fbd8-a963-11e3-8f65-6237236abe01.png)

![screen shot 2014-03-11 at 11 19 01 pm](https://f.cloud.github.com/assets/1516018/2391162/5d6a4984-a963-11e3-812d-cfe1d3f6b00b.png)

**Comment by jpic** [comment] 2015-06-01 00:12
I think this is fixed on 2.2.0 series, not sure because I can't reproduce.

Could you please open a new issue if that happens with 2.2.0 series ? 

Thanks

**Closed by jpic** 2015-06-01 00:12 UTC
