### ISSUE TITLE
Incorrect case sql expression in 2.1.1 in postgresql

### ISSUE THREAD

**Issue by vikagalkina** [yourlabs/django-autocomplete-light#420] opened 2015-05-22 21:11 UTC
In autocomplete_light.autocomplete.model.AutocompleteModel.order_choices incorrect sql 
'WHEN %s="%s" THEN %s' because postgresql in expression like 'when id="123"' parse "123" like a column and raise exception that column "123" not found.

**Comment by jpic** [comment] 2015-05-23 08:43
Duplicate of #419

**Closed by jpic** 2015-05-23 08:43 UTC

**Comment by jpic** [comment] 2015-05-26 09:07
Could you try with 2.2.0rc1 which was [released yesterday](http://blog.yourlabs.org/post/119860038918/django-autocomplete-light-2-2-0rc1-release-notes) ? 

Thanks.
