### ISSUE TITLE
The language file for "./i18n/en-us" could not be automatically loaded. A fallback will be used instead

### ISSUE THREAD

**Issue by busla** [yourlabs/django-autocomplete-light#782] opened 2016-12-19 21:39 UTC
On a clean install, Django 1.10, I get the following message:

`The language file for "./i18n/en-us" could not be automatically loaded. A fallback will be used instead`

I see that in the src and dist folders the translation files don´t have the sublanguage suffixes.

What´s the best practice here?

**Comment by kevin-brown** [comment] 2016-12-19 21:44
This is a warning, triggered by Select2, and it can be safely ignored.

**Comment by busla** [comment] 2016-12-19 22:48
I would like to resolve the issue since its affecting the load speed of the admin site. The static files seem to wait for this to load and with multiple inlines its really having an impact.

**Comment by jforaker** [comment] 2017-05-25 15:21
This definitely affects "time to interactive," especially when you have multiple fields on the page. Sometimes we have upwards of 10-20 and its very noticeable. I don't think "it can be safely ignored" is a good assessment of the issue.

**Comment by jpic** [comment] 2017-05-25 15:32
Pull requests will be reviewed.

Perhaps something can be done with #746

**Comment by jforaker** [comment] 2017-05-25 16:53
Just to note when you change the value to `<html lang="en">` versus `<html lang="en-US">` the warning goes away (and gain a slight performance increase in the case of many select2 fields on the page).

**Comment by wgordon17** [comment] 2019-02-28 23:04
@jforaker That unfortunately no longer seems to be the case :/

**Comment by pedrofaria09** [comment] 2019-03-27 17:55
Any update on this situation? Unfortunately @jforaker solution don't solve the problem for now :(

**Comment by pascalvogel1992** [comment] 2019-04-20 18:15
I have a similar problem with using a localization of Select2. Is it possible to set the language in JavaScript after the page has loaded?

**Comment by wgordon17** [comment] 2019-04-21 00:04
I managed to find a pretty easy way around this, you can specify the language using `data-` attributes to specify [Select2 configuration](https://select2.org/configuration/data-attributes). The implementation is very is easy and looks like:

```python
autocomplete.ModelSelect2Multiple(
    url='example.com',
    attrs={'data-language': 'en'}
)
```

**Comment by pascalvogel1992** [comment] 2019-04-21 06:58
> I managed to find a pretty easy way around this, you can specify the language using `data-` attributes to specify [Select2 configuration](https://select2.org/configuration/data-attributes). The implementation is very is easy and looks like:
> 
> ```python
> autocomplete.ModelSelect2Multiple(
>     url='example.com',
>     attrs={'data-language': 'en'}
> )
> ```

This does seem to work for English but I am trying to set the language to German using the way you are describing. This gets me the following error:

<img width="280" alt="Bildschirmfoto 2019-04-21 um 08 57 42" src="https://user-images.githubusercontent.com/33606756/56466517-921c5f80-6413-11e9-8154-a56307bb6319.png">

**Comment by wgordon17** [comment] 2019-04-22 13:41
It looks like `dal` will only load the specific Javascript that you have enabled for your project (https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/widgets.py#L45).

You may have to manually load the static file from `admin/js/vendor/select2/i18n/%s.js`

These are the languages supported by the Django Admin `select2` module (which is what this project uses): https://github.com/django/django/tree/master/django/contrib/admin/static/admin/js/vendor/select2/i18n

**Comment by pascalvogel1992** [comment] 2019-04-27 11:05
> It looks like `dal` will only load the specific Javascript that you have enabled for your project (https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/widgets.py#L45).
> 
> You may have to manually load the static file from `admin/js/vendor/select2/i18n/%s.js`
> 
> These are the languages supported by the Django Admin `select2` module (which is what this project uses): https://github.com/django/django/tree/master/django/contrib/admin/static/admin/js/vendor/select2/i18n

Thanks for the answer. Could you kindly give me a pointer as to how to load the file and at where?

**Comment by jpic** [comment] 2019-04-27 18:39
Maybe "backport" (copy) them from upstream django version into your project ?

**Comment by wgordon17** [comment] 2019-04-28 02:14
Try adding the `Media` class within your Form class...something like

```python
class MyForm(forms.ModelForm):
    my_field = autocomplete.ModelSelect2(
        url='/example/',
        attrs={'data-language': 'de'}
    )

    class Media:
        js = ('static/admin/js/vendor/select2/i18n/de.js',)
```

This assumes `STATIC_URL = '/static/'`. I haven't tested, but the [Media](https://docs.djangoproject.com/en/2.2/topics/forms/media/) should enforce the JS you need to load.

**Comment by pascalvogel1992** [comment] 2019-04-28 08:17
> Try adding the `Media` class within your Form class...something like
> 
> ```python
> class MyForm(forms.ModelForm):
>     my_field = autocomplete.ModelSelect2(
>         url='/example/',
>         attrs={'data-language': 'de'}
>     )
> 
>     class Media:
>         js = ('static/admin/js/vendor/select2/i18n/de.js',)
> ```
> 
> This assumes `STATIC_URL = '/static/'`. I haven't tested, but the [Media](https://docs.djangoproject.com/en/2.2/topics/forms/media/) should enforce the JS you need to load.

I think the language file is found but I get another error message:

<img width="573" alt="Bildschirmfoto 2019-04-28 um 10 15 42" src="https://user-images.githubusercontent.com/33606756/56861177-c2797600-699e-11e9-8d51-f009b1024a9a.png">

Is it possible jQuery is not being found (being loaded at the wrong spot possibly)?

**Comment by wgordon17** [comment] 2019-04-29 14:40
So, I tested this locally, and as you can see
![image](https://user-images.githubusercontent.com/22222756/56903715-d25e8c00-6a6a-11e9-982c-7753c8f374ce.png)
jQuery is still being loaded first.

Where I think the problem is comes from [the way django-autocomplete loads the `select2` library](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/static/autocomplete_light/jquery.init.js). Basically they don't use the global `jQuery` object, they use they're own version, so then when you load the language file, it doesn't have the `select2` object attached to `jQuery.fn`.

I'm honestly not familiar enough with django-autocomplete to know if there's a way around this. Perhaps someone more familiar with the codebase can help out?

**Comment by jpic** [comment] 2019-04-29 15:44
Do you get better result with the fix_782 branch ?
Note that it requires you to clone submodule

**Comment by wgordon17** [comment] 2019-04-29 17:12
@jpic That doesn't seem to address @pascalvogel1992's specific problem.

I know this issue was originally opened because `django-autocomplete-light` is looking for a `en-us.js` file, which doesn't exist. I actually think the _specific_ fix for this issue would be to use something like [`finders`](https://docs.djangoproject.com/en/2.2/ref/contrib/staticfiles/#finders-module) in [`widgets.py`](https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/widgets.py#L44) to see if the file exists, and then try stripping out the `-us` part and trying again. I wish I could say you could _always_ strip out `-<thing>`, but apparently some of them [do exist](https://github.com/django/django/tree/master/django/contrib/admin/static/admin/js/vendor/select2/i18n).

Anyway, it looks like @pascalvogel1992's issue is they're trying to use the `de` language for Select2, but it's not the project default set in `settings.LANGUAGE_CODE`. Because both `master` and `fix_782` work for me if I have `settings.LANGUAGE_CODE` set to `"de"`. But with `settings.LANGUAGE_CODE = "en-us"`, and using my [`attrs` hack](https://github.com/yourlabs/django-autocomplete-light/issues/782#issuecomment-487334627) to override the language to `de`, it does not seem to work as expected.

**Comment by pascalvogel1992** [comment] 2019-04-29 17:17
`Anyway, it looks like @pascalvogel1992's issue is they're trying to use the de language for Select2, but it's not the project default set in settings.LANGUAGE_CODE. Because both master and fix_782 work for me if I have settings.LANGUAGE_CODE set to "de". But with settings.LANGUAGE_CODE = "en-us", and using my attrs hack to override the language to de, it does not seem to work as expected.`

Reading this comment I just realized that I am using the language code 'de-DE' instead of 'de' in my settings.py. After changing the language code to 'de' everything works now... I'm not sure where I got this de-DE language code. It did work and set the admin language etc. to German that's why I never considered it might be the wrong choice in this case.

**Comment by jpic** [comment] 2019-04-29 17:48
Is this maybe the method you want to hack: https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/widgets.py#L40-L66

**Comment by wgordon17** [comment] 2019-04-29 17:55
Yeah, that was where I was thinking. It doesn't have to be to smart, just a very basic
```
does this exist?
    strip -<thing>
    does this exist now?
        eh screw it
```

I think that would at least be enough to close this issue and prevent this specific error message

**Comment by jpic** [comment] 2019-04-29 18:59
Question: are you all on django < 2.0 ?

**Comment by wgordon17** [comment] 2019-04-29 19:35
I'm on 2.1

**Comment by jpic** [comment] 2019-04-29 19:59
So, do you think this should call finders.find every time a select2 widget
is displayed ?

**Comment by wgordon17** [comment] 2019-04-29 20:18
Ewww, that's ugly. Somehow that wasn't hitting me that it was called on every display. What about doing something even more naive? Just include both the hypenated and non-hyphenated versions? Something like

```python
def media(self):
    """Return JS/CSS resources for the widget."""
    extra = '' if settings.DEBUG else '.min'
    i18n_name = SELECT2_TRANSLATIONS.get(translation.get_language())
    i18n_file = (
        'admin/js/vendor/select2/i18n/%s.js' % i18n_name,
    ) if i18n_name else ()
    if '-' in i18n_name:
        i18n_file = i18n_file + (
            'admin/js/vendor/select2/i18n/%s.js' % i18n_name.split('-')[0],
        )
```
This way the browser will just 404 on the incorrect one, and still end up loading the correct one.

**Comment by pascalvogel1992** [comment] 2019-04-29 20:37
I‘m on 2.2 if it helps.

**Comment by jpic** [comment] 2019-04-29 21:16
In this case, how do you suggest we modify select2 initialization to load 2
languages ?
https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/static/autocomplete_light/select2.js#L77

**Comment by jpic** [comment] 2019-04-29 21:16
Otherwise would it work to call the finder and set a class level dict
attribute for caching ?

**Comment by wgordon17** [comment] 2019-05-01 16:18
Hmm, Select2 isn't making this easy for us 😆 

I think you have the right idea with caching. I'm even thinking a module-level function with [lru_cache](https://docs.python.org/3/library/functools.html#functools.lru_cache) should prevent the biggest performance hit

**Comment by jpic** [comment] 2019-05-02 07:38
Sure, do you want to make a pull request now that you're well aware of the
situation ?

**Closed** 2019-05-03 18:33 UTC
