### ISSUE TITLE
"Creating choices that don’t exist" feature incomplete

### ISSUE THREAD

**Issue by litchfield** [yourlabs/django-autocomplete-light#604] opened 2016-02-26 06:40 UTC
This feature seems incomplete. Here's a few issues --

- An type error occurred as a method was expecting int pks (not the new string value). 
- The field name "name" has been hardcoded into the CreateModelField. 
- New choices are created but show as numbers.

**Comment by jpic** [comment] 2016-02-26 12:28
Hi,

I couldn't reproduce your issue on the demo:

- open
http://dal-yourlabs.rhcloud.com/admin/select2_one_to_one/testmodel/51/change/
- put something new in the input, ie. 'simontest123', select the 'Create
"simontest123"',
- the select field displays 'Create "simontest123"',
- click to save the form,
- the select field displays 'simontest123'

Is there any way you could fork the project and provide an example app to
reproduce it ?

For the name field, that's encapsulated in the create_value method which
you can override:
https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal/fields.py#L9-L11

A PR would be great to mention it in the documentation, are you up for it ?

**Comment by litchfield** [comment] 2016-03-01 04:19
Thanks for the response @jpic, but I ended up using typeahead instead. The solution was inadequate for me, I didn't like the "Create..." UI, or how new models were saved prior to the whole form being saved successfully. I worked around the int() errors and numbers. But I think a different approach is needed.

FYI the errors were seen using django 1.9, on a very simple id & name table.

**Comment by jpic** [comment] 2016-03-01 12:26
On Tue, Mar 1, 2016 at 5:19 AM, Simon Litchfield <notifications@github.com>
wrote:

> Thanks for the response @jpic <https://github.com/jpic>, but I ended up
> using typeahead instead. The solution was inadequate for me, I didn't like
> the "Create..." UI, or how new models were saved prior to the whole form
> being saved successfully. I worked around the int() errors and numbers. But
> I think a different approach is needed.
>
So, what happens if two different persons want to create the same object at
the same time ?

How do you handle the race condition and avoid having duplicate objects in
the database ?

How did you work around the int() error, does your workaround support
non-int primary keys ?

**Comment by jpic** [comment] 2016-03-04 23:49
Closing in favor of #609

**Closed by jpic** 2016-03-04 23:49 UTC

**Comment by jpic** [comment] 2016-03-05 01:03
This has changed in 3.1 !
